//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiParcare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parcare
    {
        public int LocID { get; set; }
        public string StareLoc { get; set; }
    }
}
